Add basic relation
Mapotempo/couchbase-orm pull request #51
Opened 2022-09-20 11:52 UTC by simkim

2022-09-20 12:47 UTC, pimpin commented on lib/couchbase-orm/relation.rb
> +            def r_all
Why this name an not a simple `all` ?

2022-09-20 12:53 UTC, simkim commented on lib/couchbase-orm/relation.rb
> +                CouchbaseOrm_Relation.new(**initializer_arguments.merge(where: conds))
Yes, on the todo

2022-09-21 15:42 UTC, giallon requested changes

2022-09-21 15:42 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +            def build_order
pass to private all build methods

2022-09-21 15:42 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +            def merge_where(conds, _not = false)
pass to private

2022-09-21 15:42 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +            def merge_order(*lorder, **horder)
pass to private

2022-09-21 15:42 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +                CouchbaseOrm::logger.debug("Delete all: #{self}")
pass debug message to methods

2022-09-21 16:07 UTC, giallon requested changes

2022-09-21 16:07 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +            def build_limit
pass build_limit to private

2022-09-21 16:07 UTC, giallon commented on lib/couchbase-orm/relation.rb
> +            def initializer_arguments
pass initializer_arguments to private

2022-09-21 16:10 UTC, giallon approved these changes

2022-09-22 09:36 UTC, merged