Array, Nested, Array of Nested, Nested of Nested
Mapotempo/couchbase-orm pull request #52
Opened 2022-09-22 12:17 UTC by simkim

2022-09-22 13:39 UTC, pimpin reviewed
Some cosmetics suggestions on empty lines after early raise or return.

2022-09-22 13:39 UTC, pimpin commented on lib/couchbase-orm/types/array.rb
> +                values.map(&@type_class.method(:serialize))
```suggestion
                return [] if values.nil?

                values.map(&@type_class.method(:serialize))
```

2022-09-22 13:39 UTC, pimpin commented on lib/couchbase-orm/types/array.rb
> +              values.map(&@type_class.method(:cast))
```suggestion
            def cast(values)
              return [] if values.nil?
              raise ArgumentError, "#{values.inspect} must be an array" unless values.is_a?(::Array)
              
              values.map(&@type_class.method(:cast))
```

2022-09-22 13:39 UTC, pimpin commented on lib/couchbase-orm/types/nested.rb
> +                @model_class = type
```suggestion
                raise ArgumentError, "type is not a class : #{type.inspect}" unless type.is_a?(Class)

                @model_class = type
```

2022-09-29 12:25 UTC, fab-girard requested changes
Can you add 2 sections for array and nested attributes with examples in readme please?

2022-09-29 19:13 UTC, avsej commented
when this PR will be merged, I will rebase my #55 and fix conflicts if there will be detected.

2022-09-29 19:14 UTC, avsej approved these changes

2022-10-11 06:48 UTC, merged